service: no-meat-may-app

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-cloudside-plugin
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  serverless-offline:
    port: 4000
  AWS_ACCOUNT: 592363304474
  DB_HOST:
    Fn::GetAtt: [PostgreSqlRDSInstance, Endpoint.Address]
  VPC_CIDR: 10
  ENV: ${opt:env, 'dev'}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:env, 'dev'}
  role: LambdaRole
  region: ap-southeast-2
  cfnRole: arn:aws:iam::592363304474:role/nmm-serverless-deploy-role
  timeout: 10
  logRetentionInDays: 14
  # Guesstimate - AWS recommends load testing &
  # checking MAX MEMORY USED to adjust the size
  memorySize: 512
  environment:
    DB_HOST: ${opt:LOCAL_DB_HOST, self:custom.DB_HOST}
    ENV: ${self:custom.ENV}

layers:
  graphql:
    package:
      artifact: lambda_layers/graphql_node_modules.zip

package:
  exclude:
    - node_modules/**

# Raw AWS CloudFormation goes here
resources:
  Resources:
    LambdaRole: ${file(./serverlessResources/LambdaRole.yml)}
    InternetGateway: ${file(./serverlessResources/InternetGateway.yml)}
    VPCGatewayAssociation: ${file(./serverlessResources/VPCGatewayAssociation.yml)}
    VPC: ${file(./serverlessResources/VPC.yml)}
    SubnetA: ${file(./serverlessResources/SubnetA.yml)}
    SubnetB: ${file(./serverlessResources/SubnetB.yml)}
    SubnetC: ${file(./serverlessResources/SubnetC.yml)}
    SubnetGroup: ${file(./serverlessResources/SubnetGroup.yml)}
    SecurityGroupLambdaToRDS: ${file(./serverlessResources/SecurityGroupLambdaToRDS.yml)}
    SecurityGroupBastionToRDS: ${file(./serverlessResources/SecurityGroupBastionToRDS.yml)}
    SecurityGroupLambda: ${file(./serverlessResources/SecurityGroupLambda.yml)}
    SecurityGroupBastion: ${file(./serverlessResources/SecurityGroupBastion.yml)}
    RouteTableSubnetA: ${file(./serverlessResources/RouteTableSubnetA.yml)}
    RouteTableSubnetB: ${file(./serverlessResources/RouteTableSubnetB.yml)}
    RouteTableSubnetC: ${file(./serverlessResources/RouteTableSubnetC.yml)}
    RouteA: ${file(./serverlessResources/RouteA.yml)}
    RouteB: ${file(./serverlessResources/RouteB.yml)}
    RouteC: ${file(./serverlessResources/RouteC.yml)}
    RouteTableAssociationSubnetA: ${file(./serverlessResources/RouteTableAssociationSubnetA.yml)}
    RouteTableAssociationSubnetB: ${file(./serverlessResources/RouteTableAssociationSubnetB.yml)}
    RouteTableAssociationSubnetC: ${file(./serverlessResources/RouteTableAssociationSubnetC.yml)}
    NATSubnetA: ${file(./serverlessResources/NATSubnetA.yml)}
    EIPSubnetA: ${file(./serverlessResources/EIPSubnetA.yml)}
    NATSubnetB: ${file(./serverlessResources/NATSubnetB.yml)}
    EIPSubnetB: ${file(./serverlessResources/EIPSubnetB.yml)}
    PostgreSqlRDSInstance: ${file(./serverlessResources/PostgreSqlRDSInstance.yml)}

functions:
  graphql:
    handler: src/lambda.graphql
    events:
    - http:
        path: nmm-app
        method: post
        cors:
          origin: ${opt:secureOrigin, 'http://localhost:3000'}
          headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - access-control-allow-origin
              - apollographql-client-name
              - apollographql-client-version
          allowCredentials: true
    - http:
        path: nmm-app
        method: get
        cors:
          origin: ${opt:secureOrigin, 'http://localhost:3000'}
          headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - access-control-allow-origin
              - apollographql-client-name
              - apollographql-client-version
          allowCredentials: true
    - http:
        path: playground
        method: get
        cors: true
    - http:
        path: playground
        method: post
        cors: true
    vpc:
      securityGroupIds:
        - !GetAtt SecurityGroupLambda.GroupId
      subnetIds:
        - Ref: SubnetA
        - Ref: SubnetB
    layers:
    # Name = <name of layer>LambdaLayer
      - { Ref: GraphqlLambdaLayer }
